replace into s_game_type(gametype,gameid,title,state,hot) values(4,240,'xiyouzhengba_918',1,190);
replace into s_game_type(gametype,gameid,title,state,hot) values(4,241,'zhanwubusheng',1,190);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 125, "泰国神游", 1, 130);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 126, "足球嘉年华", 1, 120);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 127, "斩五门", 1, 110);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 128, "斯巴达", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 129, "复活节", 1, 100);

replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 130, "拉力赛", 1, 190);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 131, "拜年", 1, 140);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 132, "五福门", 1, 120);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 133, "红绿灯", 1, 150);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 134, "金龙赐福", 1, 200);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 135, "蒸汽塔", 1, 200);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 136, "胜利", 1, 220);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 137, "花园", 1, 210);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 138, "阿拉丁", 1, 210);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 139, "船长", 1, 280);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 140, "勇敢传说", 1, 400);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 141, "万圣节", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 142, "万圣节惊喜", 1, 100);

replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 144, "niannianyouyu", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 145, "樱桃的爱", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 146, "qiangzhoujiux", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 147, "zhaocaijinbao", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 148, "印度神话", 1, 300);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 149, "冰雪世界", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 150, "海洋世界", 1, 120);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 151, "农场故事", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 152, "珍宝岛", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 153, "kuangrejinqian", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 154, "石器时代", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 155, "精灵花园", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 156, "闪亮之星", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 159, "魔法师", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 160, "haiyangtiantang", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 161, "laola", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 162, "jijiewenhou", 1, 100);

replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 163, "ailisi", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 165, "sunwukong", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 166, "jinqianwa", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 167, "jixing", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 168, "发大财", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 169, "zhuangzhily", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 170, "西部牧场", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 238, "五龙", 1, 100);
replace into `s_game_type` (gametype, gameid, title, state, hot)  VALUES (2, 162, "jijiewenhou", 1, 100);
